# Apple sample code swiftlint configuration.

excluded: # paths to ignore during linting.
  - build

line_length: 200

function_body_length: 1000

number_separator:
  minimum_length: 5

force_cast: warning

identifier_name:
  excluded:
    - up

large_tuple:
  warning: 4
  error: 5

cyclomatic_complexity:
  warning: 35
  error: 40

trailing_whitespace:
  ignores_empty_lines: true

maxEmptyLines: 4
  
opt_in_rules:
  - attributes
  
  - closure_end_indentation
  - closure_spacing
  
  - empty_count
  - explicit_init
  
  - first_where
  
  - nimble_operator
  - number_separator
  
  - overridden_super_call
  - operator_usage_whitespace
  - object_literal
  
  - prohibited_super_call
  
  - redundant_nil_coalescing
  
disabled_rules:
  - trailing_newline
  - operator_whitespace
  - fallthrough
  - multiple_closures_with_trailing_closure
  - empty_parentheses_with_trailing_closure
  - switch_case_alignment
  - type_body_length
  - file_length
  - line_length
  - vertical_whitespace
  - object_literal
