//
//  Autogenerated by update-private-headers.py
//  Copyright © 2020 Apple Inc. All rights reserved.

#if INTERNAL_SDK_AVAILABLE

#import <HearingUtilities/HUNoiseSettings.h>
#import <HearingUtilities/HUComfortSoundsSettings.h>
#import <HearingUtilities/HearingUtilities.h>

#else

#import "HUNoiseSettings.h"
#import "HUComfortSoundsSettings.h"
#import "HearingUtilities.h"

#endif
