//
//  Autogenerated by update-private-headers.py
//  Copyright © 2020 Apple Inc. All rights reserved.

#if INTERNAL_SDK_AVAILABLE

#import <AudioDataAnalysis/ADAMAudioDataAnalysisDefines.h>
#import <AudioDataAnalysis/ADAMAudioDataAnalysisSettings.h>

#else

#import "ADAMAudioDataAnalysisDefines.h"
#import "ADAMAudioDataAnalysisSettings.h"

#endif
