//
//  Autogenerated by update-private-headers.py
//  Copyright © 2023 Apple Inc. All rights reserved.

#if RK_APPLE_INTERNAL

#if ORK_INTERNAL_SDK_AVAILABLE

#import <UIKit/UIWindowScene_Private.h>
#import <UIKit/UIResponder_Private.h>

#else

#import "UIWindowScene_Private.h"
#import "UIResponder_Private.h"

#endif

#endif
