//
//  Autogenerated by update-private-headers.py
//  Copyright © 2019 Apple Inc. All rights reserved.

#if ORK_INTERNAL_SDK_AVAILABLE

#import <AVFoundation/AVOutputDeviceDiscoverySession.h>
#import <AVFoundation/AVOutputDevice.h>
#import <AVFoundation/AVOutputDeviceModelSpecificKeys.h>
#import <AVFoundation/AVOutputContext.h>
#import <AVFoundation/AVOutputContext_Private.h>

#else

#import "AVOutputDeviceDiscoverySession.h"
#import "AVOutputDevice.h"
#import "AVOutputDeviceModelSpecificKeys.h"
#import "AVOutputContext.h"
#import "AVOutputContext_Private.h"

#endif
