//
//  Autogenerated by update-private-headers.py
//  Copyright © 2019 Apple Inc. All rights reserved.

#if RK_APPLE_INTERNAL

#if ORK_INTERNAL_SDK_AVAILABLE

#import <BluetoothManager/BluetoothManager.h>
#import <BluetoothManager/BluetoothDevice.h>

#else

#import "BluetoothManager.h"
#import "BluetoothDevice.h"

#endif

#endif
