//
//  Autogenerated by update-private-headers.py
//  Copyright © 2019 Apple Inc. All rights reserved.
// apple-internal

#if APPLE_INTERNAL

#if ORK_INTERNAL_SDK_AVAILABLE

#import <Celestial/AVSystemController.h>

#else

#import "AVSystemController.h"

#endif

#endif
